---
name: Build Docker
on:
  push:
    branches: ["*"]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Build and push docker image"
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
    runs-on: ubuntu-latest
    outputs:
      docker-hash: ${{ steps.build-and-push.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # # Set up BuildKit Docker container builder to be able to build
      # # multi-platform images and export cache
      # # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Add metadata to image
        run: |
          cat << EOF > metadata.json
          ${{ steps.meta.outputs.json }}
          EOF

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          load: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
